name: 'gcs-cache-action'
description: 'GitHub Actions wrapper around gcs-cacher'
author: 'Shakr Media Co., Ltd.'
inputs:
  path:
    required: true
    description: 'path to cache (must be directory)'
  key:
    required: true
    description: 'primary cache key'
  restore_keys:
    required: true
    description: 'multiline string of cache keys for partial matching'
runs:
  using: 'node16'
  main: 'dist/restore/index.js'
  post: 'dist/save/index.js'
